// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nysmrlayvqprbsmfuyzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55c21ybGF5dnFwcmJzbWZ1eXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDI0NzQsImV4cCI6MjA3MDA3ODQ3NH0.fLo5KF72NV8QjosrydUm7Zcx0nzny1RZ3lHfHaD1X0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});